media:
  input: public/images
  output: /images

content:
  - name: about
    label: About Page
    type: file
    path: src/data/about.yaml
    format: yaml
    fields:
      - name: title
        label: Page Title
        type: string
        required: true
      - name: subtitle
        label: Subtitle
        type: string
        required: true
      - name: story
        label: Story Section
        type: object
        fields:
          - name: title
            label: Section Title
            type: string
          - name: paragraphs
            label: Paragraphs
            type: text
            list: true
      - name: skills
        label: Skills Section
        type: object
        fields:
          - name: intro
            label: Introduction Text
            type: string
          - name: categories
            label: Skill Categories
            type: object
            list: true
            fields:
              - name: name
                label: Category Name
                type: string
              - name: description
                label: Description
                type: string
              - name: items
                label: Skills
                type: string
                list: true
      - name: interests
        label: Interests Section
        type: object
        fields:
          - name: intro
            label: Introduction
            type: string
          - name: items
            label: Interests
            type: string
            list: true
          - name: footer
            label: Footer Text
            type: string
      - name: contact
        label: Contact Section
        type: object
        fields:
          - name: intro
            label: Introduction
            type: text
          - name: cta
            label: Call to Action
            type: text
          - name: email
            label: Email Address
            type: string
          - name: linkedin
            label: LinkedIn URL
            type: string
          - name: github
            label: GitHub URL
            type: string

  - name: blog
    label: Blog Posts
    type: collection
    path: src/content/blog
    format: yaml-frontmatter
    filename: "{slug}.md"
    view:
      fields: [title, pubDate, draft]
      primary: title
      sort: pubDate
      order: desc
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        required: true
      - name: pubDate
        label: Publish Date
        type: date
        required: true
      - name: updatedDate
        label: Updated Date
        type: date
      - name: heroImage
        label: Hero Image
        type: image
      - name: draft
        label: Draft
        type: boolean
        default: false
      - name: tags
        label: Tags
        type: string
        list: true

  - name: projects
    label: Projects
    type: collection
    path: src/content/projects
    format: yaml-frontmatter
    filename: "{slug}.md"
    view:
      fields: [title, category, status, order]
      primary: title
      sort: order
      order: asc
    fields:
      - name: title
        label: Project Name
        type: string
        required: true
      - name: description
        label: Description
        type: text
        required: true
        description: Short description shown in the project list
      - name: category
        label: Category
        type: select
        required: true
        description: Used for filtering on the projects page
        options:
          values:
            - value: enterprise
              label: Enterprise IT
            - value: web
              label: Web & Digital
            - value: writing
              label: Writing & Culture
            - value: hardware
              label: Hardware & Infrastructure
            - value: automation
              label: Automation
            - value: consultancy
              label: Consultancy
      - name: status
        label: Status
        type: select
        required: true
        options:
          values:
            - value: active
              label: Live
            - value: development
              label: In Development
            - value: planned
              label: Planned
            - value: archived
              label: Archived
      - name: order
        label: Display Order
        type: number
        default: 99
        description: Lower numbers appear first
      - name: heroImage
        label: Hero Image
        type: image
      - name: tech
        label: Technologies
        type: string
        list: true
      - name: liveUrl
        label: Live URL
        type: string
      - name: repoUrl
        label: Repository URL
        type: string
      - name: role
        label: Your Role
        type: string
      - name: year
        label: Year
        type: string

settings:
  content:
    merge: true
