media:
  input: public
  output: /

content:
  - name: blog
    label: Blog Posts
    type: collection
    path: src/content/blog
    format: yaml-frontmatter
    filename: '{year}-{month}-{day}-{title}.md'
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
      - name: pubDate
        label: Published Date
        type: date
        required: true
      - name: heroImage
        label: Hero Image
        type: image
      - name: body
        label: Body
        type: rich-text
        required: true
    view:
      fields: [ title, pubDate ]
      primary: title
      sort: [ pubDate, title ]
      default:
        sort: pubDate
        order: desc

  - name: about
    label: About Page
    type: file
    path: src/pages/about.astro
    fields:
      - name: body
        label: Body
        type: rich-text

settings:
  content:
    merge: true
